version: '3'
services:
  php:
    image: php:7.3-apache
    container_name: hello-docker
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./public:/var/www/html
    networks:
      - pangolin
    restart: unless-stopped

networks:
  pangolin:
    external: true
