version: '3'
services:
    helloworld:
        container_name: helloworld
        image: crccheck/hello-world
        expose:
            - 8000

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 8080:80
            - 443:443
        volumes:
            - /home/portainer/hello-docker/nginx.conf:/etc/nginx/nginx.conf
